export const menus = [
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 20,
      "name": "Dashboard",
      "icon": "icon-dasbhoard",
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.dashboard",
      "key": "dashboard",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 21,
          "name": "Tổng quan dự án",
          "icon": "icon-crypto",
          "parent": 20,
          "isParent": null,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/dashboard/report-agency",
          "alias": "sidebar.dashboard.crypto",
          "key": "dashboard/report-agency",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 54,
          "name": "Báo cáo khách hàng",
          "icon": "icon-crypto",
          "parent": 20,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/dashboard/report-customer",
          "alias": "sidebar.main.reportcustomer",
          "key": "main/report-customer",
          "action": "crud"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 22,
      "name": "Hệ thống",
      "icon": null,
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.main",
      "key": "main",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 23,
          "name": "Phân quyền",
          "icon": "icon-widgets",
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/main/roles",
          "alias": "sidebar.roles",
          "key": "main/roles",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 24,
          "name": "Người dùng",
          "icon": "icon-user",
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": "user",
          "active": true,
          "isView": null,
          "url": "/main/user",
          "alias": "sidebar.user",
          "key": "main/user",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 25,
          "name": "Đại lý",
          "icon": "icon-crm",
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": "agency",
          "active": true,
          "isView": null,
          "url": "/main/agency",
          "alias": "sidebar.agency",
          "key": "main/agency",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 51,
          "name": "Cấu hình",
          "icon": "icon-setting",
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/main/config",
          "alias": "sidebar.main.config",
          "key": "main/config",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 56,
          "name": "Thông báo",
          "icon": "icon-notification",
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/main/notification",
          "alias": "sidebar.main.notification",
          "key": "sidebar.main.notification",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 63,
          "name": "Khách hàng đặt căn",
          "icon": "icon-graduation",
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": "customer",
          "active": true,
          "isView": null,
          "url": "/main/customer",
          "alias": "sidebar.main.customer",
          "key": "sidebar.main.customer",
          "action": "cru"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 67,
          "name": "Lịch sử hệ thống",
          "icon": null,
          "parent": 22,
          "isParent": false,
          "sequence": null,
          "model": "actionlog",
          "active": true,
          "isView": null,
          "url": "/main/actionlog",
          "alias": "sidebar.main.actionlog",
          "key": "sidebar.main.actionlog",
          "action": "r"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 26,
      "name": "E-learning",
      "icon": null,
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.inBuiltApp",
      "key": "agency",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 27,
          "name": "Lớp học",
          "icon": "icon-email",
          "parent": 26,
          "isParent": false,
          "sequence": null,
          "model": "class",
          "active": true,
          "isView": null,
          "url": "/agency/classroom",
          "alias": "sidebar.manage_class",
          "key": "agency/classroom",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 61,
          "name": "Banner App",
          "icon": "icon-card",
          "parent": 26,
          "isParent": false,
          "sequence": null,
          "model": "bannerapp",
          "active": true,
          "isView": null,
          "url": "/agency/bannerapp",
          "alias": "sidebar.agency.bannerapp",
          "key": "/agency/bannerapp",
          "action": "cru"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 62,
          "name": "Popup App",
          "icon": "icon-badge",
          "parent": 26,
          "isParent": false,
          "sequence": null,
          "model": "popupapp",
          "active": true,
          "isView": null,
          "url": "/agency/popupapp",
          "alias": "sidebar.agency.popupapp",
          "key": "sidebar.agency.popupapp",
          "action": "cru"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 64,
          "name": "Sự kiện App",
          "icon": null,
          "parent": 26,
          "isParent": false,
          "sequence": null,
          "model": "events",
          "active": true,
          "isView": null,
          "url": "/agency/eventapp",
          "alias": "sidebar.agency.eventapp",
          "key": "sidebar.agency.eventapp",
          "action": "cru"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 28,
      "name": "Quản lý dự án",
      "icon": null,
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.customViews",
      "key": "manage-project",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 29,
          "name": "Dự án",
          "icon": "icon-auth-screen",
          "parent": 28,
          "isParent": false,
          "sequence": null,
          "model": "project",
          "active": true,
          "isView": null,
          "url": "/manage-project/project",
          "alias": "sidebar.manage_project",
          "key": "manage-project/project",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 30,
          "name": "Video dự án",
          "icon": "icon-menu-right",
          "parent": 28,
          "isParent": false,
          "sequence": null,
          "model": "videoproject",
          "active": true,
          "isView": null,
          "url": "/manage-project/videoproject",
          "alias": "sidebar.video_project",
          "key": "manage-project/videoproject",
          "action": "crud"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 31,
      "name": "Tình trạng dự án",
      "icon": null,
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.stateProject",
      "key": "state-project",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 32,
          "name": "Checklist dự án",
          "icon": "icon-anchor",
          "parent": 31,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/state-project/checklist",
          "alias": "sidebar.stateProject.checklist",
          "key": "state-project/checklist",
          "action": "crud"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 39,
      "name": "Booking",
      "icon": "icon-company",
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": "/booking-apartment",
      "alias": "sidebar.booking",
      "key": "booking-apartment",
      "action": "crud"
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 53,
      "name": "Khách hàng",
      "icon": null,
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": "/customer-media",
      "alias": "sidebar.customer",
      "key": "customer-media",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 70,
          "name": "Khách hàng Marketing",
          "icon": null,
          "parent": 53,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/customer-media",
          "alias": "sidebar.customer-marketing",
          "key": "sidebar.customer-marketing",
          "action": "cru"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 71,
          "name": "Khách hàng VPBH",
          "icon": null,
          "parent": 53,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/customer-vpbh",
          "alias": "sidebar.customer-vpbh",
          "key": "sidebar.customer-vpbh",
          "action": "cru"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 100,
      "name": "Game",
      "icon": "icon-widgets",
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.game",
      "key": "game",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 101,
          "name": "K3 Game",
          "icon": "icon-widgets",
          "parent": 100,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/game/k3",
          "alias": "sidebar.game.k3",
          "key": "game/k3",
          "action": "crud"
        }
      ]
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 102,
      "name": "K3 Game",
      "icon": "icon-dice",
      "parent": 0,
      "isParent": false,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": "/game/k3",
      "alias": "sidebar.game.k3standalone",
      "key": "game/k3standalone",
      "action": "crud"
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 103,
      "name": "Trx",
      "icon": "icon-chart",
      "parent": 0,
      "isParent": false,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": "/game/trxwingo",
      "alias": "sidebar.game.trx",
      "key": "game/trx",
      "action": "crud"
    },
    {
      "createdAt": null,
      "updatedAt": null,
      "id": 200,
      "name": "Game",
      "icon": "icon-widgets",
      "parent": 0,
      "isParent": true,
      "sequence": null,
      "model": null,
      "active": true,
      "isView": null,
      "url": null,
      "alias": "sidebar.game.menu",
      "key": "game/menu",
      "action": "crud",
      "children": [
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 201,
          "name": "Wingo",
          "icon": "icon-widgets",
          "parent": 200,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/game/wingo",
          "alias": "sidebar.game.wingo",
          "key": "game/wingo",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 202,
          "name": "K3",
          "icon": "icon-dice",
          "parent": 200,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/game/k3",
          "alias": "sidebar.game.k3",
          "key": "game/k3",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 203,
          "name": "5d",
          "icon": "icon-widgets",
          "parent": 200,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/game/5d",
          "alias": "sidebar.game.5d",
          "key": "game/5d",
          "action": "crud"
        },
        {
          "createdAt": null,
          "updatedAt": null,
          "id": 204,
          "name": "Trx",
          "icon": "icon-chart",
          "parent": 200,
          "isParent": false,
          "sequence": null,
          "model": null,
          "active": true,
          "isView": null,
          "url": "/game/trx",
          "alias": "sidebar.game.trx",
          "key": "game/trx",
          "action": "crud"
        }
      ]
    }
  ]
